# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZYBO.xdc

# Block Designs: bd/Memory_design/Memory_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design || ORIG_REF_NAME==Memory_design}]

# IP: bd/Memory_design/ip/Memory_design_processing_system7_0_0/Memory_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_processing_system7_0_0 || ORIG_REF_NAME==Memory_design_processing_system7_0_0}]

# IP: bd/Memory_design/ip/Memory_design_blk_mem_gen_0_0/Memory_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_blk_mem_gen_0_0 || ORIG_REF_NAME==Memory_design_blk_mem_gen_0_0}]

# IP: bd/Memory_design/ip/Memory_design_axi_bram_ctrl_0_0/Memory_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Memory_design_axi_bram_ctrl_0_0}]

# IP: bd/Memory_design/ip/Memory_design_axi_smc_0/Memory_design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_axi_smc_0 || ORIG_REF_NAME==Memory_design_axi_smc_0}]

# IP: bd/Memory_design/ip/Memory_design_rst_ps7_0_50M_0/Memory_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==Memory_design_rst_ps7_0_50M_0}]

# IP: bd/Memory_design/ip/Memory_design_blk_mem_gen_0_1/Memory_design_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_blk_mem_gen_0_1 || ORIG_REF_NAME==Memory_design_blk_mem_gen_0_1}]

# IP: bd/Memory_design/ip/Memory_design_axi_bram_ctrl_1_0/Memory_design_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_axi_bram_ctrl_1_0 || ORIG_REF_NAME==Memory_design_axi_bram_ctrl_1_0}]

# IP: bd/Memory_design/ip/Memory_design_blk_mem_gen_0_2/Memory_design_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_blk_mem_gen_0_2 || ORIG_REF_NAME==Memory_design_blk_mem_gen_0_2}]

# IP: bd/Memory_design/ip/Memory_design_axi_bram_ctrl_2_0/Memory_design_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_axi_bram_ctrl_2_0 || ORIG_REF_NAME==Memory_design_axi_bram_ctrl_2_0}]

# IP: bd/Memory_design/ip/Memory_design_blk_mem_gen_1_0/Memory_design_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_blk_mem_gen_1_0 || ORIG_REF_NAME==Memory_design_blk_mem_gen_1_0}]

# IP: bd/Memory_design/ip/Memory_design_axi_bram_ctrl_3_0/Memory_design_axi_bram_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_axi_bram_ctrl_3_0 || ORIG_REF_NAME==Memory_design_axi_bram_ctrl_3_0}]

# IP: bd/Memory_design/ip/Memory_design_blk_mem_gen_0_3/Memory_design_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_blk_mem_gen_0_3 || ORIG_REF_NAME==Memory_design_blk_mem_gen_0_3}]

# IP: bd/Memory_design/ip/Memory_design_axi_bram_ctrl_4_0/Memory_design_axi_bram_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_design_axi_bram_ctrl_4_0 || ORIG_REF_NAME==Memory_design_axi_bram_ctrl_4_0}]

# XDC: bd/Memory_design/Memory_design_ooc.xdc
